### ISSUE TITLE
Add GMP to the PHP 7.3 image since it's required by a new Joomla 4 feature

### ISSUE THREAD

**Issue by nikosdion** [joomla-projects/docker-images#15]
Please change this line
https://github.com/joomla-projects/docker-images/blob/3fbad07e9755c953e77438fee5844959514ad35f/Dockerfile#L15
to instead read
```Dockerfile
RUN docker-php-ext-install gd mysqli pdo_mysql pgsql pdo_pgsql zip ldap gmp
```

The GMP extension is required by a dependency of the WebAuthn plugin from the Joomla CMS PR https://github.com/joomla/joomla-cms/pull/28094

Please see [this comment](https://github.com/joomla/joomla-cms/pull/28094#issuecomment-591490572) to understand the context of this request. Thank you!

**Comment by rdeutz** [comment]
Added build is running
