### ISSUE TITLE
delete builds

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/docker-images#22]
Are builds for PR that have been merged deleted afterwards

**Comment by HLeithner** [comment]
No, the plan is to remove it after 6 month, depending on our diskspace

**Comment by brianteeman** [comment]
ok

**Comment by HLeithner** [comment]
Now it's not only a plan it's enforced, files older then 180 days get deleted from the server.

**Comment by brianteeman** [comment]
So the next part is what happens to the html page and the links on the page

**Comment by HLeithner** [comment]
the same the complete artifacts (this includes the website) will be deleted

**Comment by brianteeman** [comment]
Great
