### ISSUE TITLE
[RFC] How this works?

### ISSUE THREAD

**Issue by sakiss** [joomla-projects/docker-images#29]
I am in the process of creating a new set of integration tests for Joomla 4 and want to test them against different php versions through their respective containers.

Examining the Dockerfile did not gave me much insights, as i am missing the way it gets/copies the Joomla files, in the container.
Also how are you connecting to the mysql db? Does it run as a separate container, in the same network.

Can you please provide any info to get the entire picture?

**Comment by HLeithner** [comment]
please look at our drone file how we test joomla https://github.com/joomla/joomla-cms/blob/4.0-dev/.drone.yml

**Comment by sakiss** [comment]
Thank you!

For anyone coming into that. This docker image can solely be used together with drone (not sure about other CIs).
Drone clones the repo and then runs commands over docker containers.
