### ISSUE TITLE
Might have a typo in Dockerfile

### ISSUE THREAD

**Issue by alexandreelise** [joomla-projects/docker-images#56]
Hello super joomlers!
Thanks for your hard work putting Joomla! in docker. I was pulling the php7.4-composer image and went into the container.
Then I type php -v and it spits out 7.3.21.  So I go to docker hub joomlaprojects/docker-images and I see the the Dockerfile corresponding to php7.4-composer en ENV variable set to 7.3.21 by default. Maybe it's intentional but just to be sure I wanted to give you my feedback just in case it was a typo.

Thanks for your time and your patience.

Stay safe super joomlers. Take care.

**Comment by HLeithner** [comment]
The php7.3-composer and php7.4-composer images are outdated. please use php7.4 directly all our docker images have composer included now.

**Comment by alexandreelise** [comment]
Ok thanks Harald.  I'll do that. Take care super joomler. Keep on the hard work. Thanks to you and the rest of the team @HLeithner
